version: '3'

services:
  postgres:
    container_name: pg_container
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "zoovbikes", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=postgres
      - APP_DB_PASS=pass
      - APP_DB_NAME=zoovbikes
    volumes:
      - ./db/init_scripts/:/docker-entrypoint-initdb.d/
      - ./db/sql/:/pg_setup/
    ports:
      - 5432:5432
  pgadmin:
    container_name: pgadmin_container
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
  free_bikes_saclay_watcher:
    container_name: free_bikes_saclay_watcher
    depends_on:
      postgres:
        condition: service_healthy
    build: ./feed_watcher/
    command: ["python3", "feed_watcher.py", "-c", "free_bike_status_saclay.json"]
    volumes:
    - ./feed_watcher/:/feed_watcher/
